[package]
name = "model"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { workspace = true, features = ["train", "vision", "tch"] }

[target.'cfg(target_os = "macos")'.build-dependencies]
walkdir = "2.5.0"
