[workspace]
members = ["model", "score", "tagger"]
resolver = "2"

[workspace.package]
version = "0.1.0-alpha2"

[workspace.dependencies]
burn = { version = "0.14" }
ratatui = { version = "*" }
crossterm = { version = "*" }
anyhow = { version = "1.0" }
