[workspace]
members = ["score", "tagger"]
resolver = "2"

[workspace.package]
version = "0.1.0-alpha3"

[workspace.dependencies]
burn = { version = "0.14" }
ratatui = { version = "*" }
crossterm = { version = "*" }
anyhow = { version = "1.0" }
image = { version = "0.25.2", default-features = false, features = [
    "jpeg",
    "png",
    "rayon",
] }
serde_json = { version = "1.0" }
bincode = { version = "1.3.3" }
clap = { version = "4.5.17", features = ["derive"] }
