[package]
name = "tagger"
version.workspace = true
edition = "2021"

[dependencies]
ratatui = { workspace = true }
crossterm = { workspace = true }
anyhow = { workspace = true }
ratatui-image = { version = "1.0.5", default-features = false, features = [
    "rustix",
] }
image = { version = "0.25.2", default-features = false, features = [
    "jpeg",
    "png",
    "rayon",
] }
walkdir = "2.5.0"
mime_guess = "2.0.5"
clap = { version = "4.5.17", features = ["derive"] }
crossbeam = "0.8.4"
serde_json = "1.0.128"
