[package]
name = "tagger"
version.workspace = true
edition = "2021"

[dependencies]
ratatui = { workspace = true }
crossterm = { workspace = true }
anyhow = { workspace = true }
ratatui-image = { version = "1.0.5", default-features = false, features = [
    "rustix",
] }
image = { version = "0.25.2", default-features = false, features = [
    "jpeg",
    "png",
    "rayon",
] }
