[package]
name = "tagger"
version.workspace = true
edition = "2021"
description = "A image tagger by iteractive comparation"

[dependencies]
ratatui = { workspace = true }
crossterm = { workspace = true }
anyhow = { workspace = true }
ratatui-image = { version = "1.0.5", default-features = false, features = [
    "rustix",
] }
serde_json = { workspace = true }
bincode = { workspace = true }
image = { workspace = true }
clap = { workspace = true }
walkdir = "2.5.0"
mime_guess = "2.0.5"
crossbeam = "0.8.4"
