[package]
name = "score"
version.workspace = true
edition = "2021"

[dependencies]
burn = { workspace = true, features = ["train", "tch"] }

[target.'cfg(target_os = "macos")'.build-dependencies]
walkdir = "2.5.0"
