[package]
name = "score"
version.workspace = true
edition = "2021"
description = "A image scorer by ResNet101"

[dependencies]
burn = { workspace = true, features = ["train", "tch"] }
serde_json = { workspace = true }
image = { workspace = true }
clap = { workspace = true }
